# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure subscription 1 (d3f014b7-9ee7-4391-ab82-7b8a96426538)'
    ScriptType: 'FilePath'
    ScriptPath: '.azure/scripts/set-deployment-token.ps1'
    ScriptArguments: '-ResourceGroupName web-app-staging -SiteName web-application-staging'
    azurePowerShellVersion: 'LatestVersion'

- task: AzureStaticWebApp@0
  inputs:
    app_location: './src/www'
    api_location: './src/api'
  env:
   azure_static_web_apps_api_token: $(ApiKey)