trigger:
- main
pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
   
stages:
- stage: Build
  displayName: 'Build & Test Stage'
  #condition: eq('1', '2')
  jobs:
  - template: azure-pipelines-build-template.yml
    parameters:
      environment: 'temp'
      resourceGroupName: 'web-application-temp'
      appName: 'web-application'
      appNameShort: 'webapp'
      
- stage: DeployPR
  displayName: 'Deploy PR Stage'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), ne(variables['System.PullRequest.PullRequestId'], 'Null'))
  dependsOn: Build
  variables:
    ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      prId: "$(System.PullRequest.PullRequestId)"
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      prId: '000'
    prUC: "PR$(prId)"
    prLC: "pr$(prId)"
  jobs:
  - template: azure-pipelines-deployment-template.yml
    parameters:
      prId: $(prId)
      environment: 'staging'
      resourceGroupName: 'webapp'
      appName: 'web-application'
      appNameShort: 'webapp'

- stage: DeployDev
  displayName: 'Deploy Dev Stage'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  dependsOn: Build
  jobs:
  - template: azure-pipelines-deployment-template.yml
    parameters:
      applicationInsightsApiKey: '$(ApplicationInsights--APIKeyDev)'

- stage: DeployStaging
  displayName: 'Deploy Staging Stage'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  dependsOn: DeployDev
  jobs:
  - template: azure-pipelines-deployment-template.yml
    parameters:
      applicationInsightsApiKey: '$(ApplicationInsights--APIKeyStaging)'
      
- stage: DeployProd
  displayName: 'Deploy Prod Stage'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  dependsOn: DeployStaging
  jobs:
  - template: azure-pipelines-deployment-template.yml
    parameters:
      applicationInsightsApiKey: '$(ApplicationInsights--APIKeyProd)'