parameters: # defaults for any parameters that aren't specified
  environment: 'staging'
  resourceGroupName: 'webapp'
  appName: 'web-application'
  appNameShort: 'webapp'

jobs:
  - job: BuildApp
    steps:

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM Template deployment: Resource Group scope'
      inputs:
        azureResourceManagerConnection: 'Azure subscription 1 (d3f014b7-9ee7-4391-ab82-7b8a96426538)'
        subscriptionId: 'd3f014b7-9ee7-4391-ab82-7b8a96426538'
        resourceGroupName: '${{parameters.resourceGroupName}}'
        location: 'West Europe'
        csmFile: '.azure/template/template.json'
        csmParametersFile: '.azure/template/parameters.json'
        overrideParameters: '-name "${{parameters.appNameShort}}-${{parameters.environment}}" -location "westeurope" -sku Standard" -skucode "Standard"'
        deploymentName: '${{parameters.appName}}-${{parameters.environment}}'

    - task: AzurePowerShell@5
      displayName: 'Get Deloyment Token' 
      inputs:
        azureSubscription: 'Azure subscription 1 (d3f014b7-9ee7-4391-ab82-7b8a96426538)'
        ScriptType: 'FilePath'
        ScriptPath: '.azure/scripts/set-deployment-token.ps1'
        ScriptArguments: '-ResourceGroupName ${{parameters.resourceGroupName}} -SiteName ${{parameters.appNameShort}}-${{parameters.environment}}'
        azurePowerShellVersion: 'LatestVersion'

    - task: AzureStaticWebApp@0
      displayName: 'Deploy Website'
      inputs:
        app_location: './src/www'
        api_location: './src/api'
      env:
        azure_static_web_apps_api_token: $(token)