# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  displayName: 'Set Environment Variables'
  inputs:
    targetType: 'inline'
    script: |
      echo '##vso[task.setvariable variable=environment]staging'
      echo '##vso[task.setvariable variable=appNameShort]webapp'
      echo '##vso[task.setvariable variable=appName]web-application'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    azureResourceManagerConnection: 'Azure subscription 1 (d3f014b7-9ee7-4391-ab82-7b8a96426538)'
    subscriptionId: 'd3f014b7-9ee7-4391-ab82-7b8a96426538'
    resourceGroupName: '$(appName)-$(environment)'
    location: 'West Europe'
    csmFile: '.azure/template/template.json'
    csmParametersFile: '.azure/template/parameters.json'
    overrideParameters: '-name "$(appNameShort)-$(environment)" -location "westeurope" -sku Standard" -skucode "Standard"'
    deploymentName: '$(appName)-$(environment)'

- task: AzurePowerShell@5
  displayName: 'Get Deloyment Token' 
  inputs:
    azureSubscription: 'Azure subscription 1 (d3f014b7-9ee7-4391-ab82-7b8a96426538)'
    ScriptType: 'FilePath'
    ScriptPath: '.azure/scripts/set-deployment-token.ps1'
    ScriptArguments: '-ResourceGroupName $(appName)-$(environment) -SiteName $(appNameShort)-$(environment)'
    azurePowerShellVersion: 'LatestVersion'

- task: AzureStaticWebApp@0
  displayName: 'Deploy Website'
  inputs:
    app_location: './src/www'
    api_location: './src/api'
  env:
   azure_static_web_apps_api_token: $(token)