parameters: # defaults for any parameters that aren't specified
  environment: 'staging'
  resourceGroupName: 'webapp'
  appName: 'web-application'
  appNameShort: 'webapp'

jobs:
  - job: BuildApp
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '6.x'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd ./src/www
          npm install
          npm run test:unit